import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto('about:blank');
    await page.goto('https://staging.tongram.app/');
    const page1Promise = page.waitForEvent('popup');
    await page.getByRole('button', { name: 'Log In' }).click();
    const page1 = await page1Promise;
    await page1.locator('#login-phone').click();
    await page1.locator('#login-phone').fill('0343602871');
    await page1.getByRole('button', { name: 'Next' }).click();
    await page1.goto('https://oauth.telegram.org/auth/push?bot_id=7086999571&origin=https%3A%2F%2Fstaging.tongram.app&request_access=true&return_to=https%3A%2F%2Fstaging.tongram.app%2F');
    await page.goto('https://staging.tongram.app/');
    await page.getByRole('banner').click();
    await page.getByRole('button', { name: 'Liêu Duy Thanh' }).click();
    await page.getByRole('button', { name: 'My Apps' }).click();
    await page.getByRole('button', { name: 'Liêu Duy Thanh' }).click();
    await page.getByRole('button', { name: 'Submit App' }).click();
    await page.getByPlaceholder('Enter your application name').click();
    await page.getByPlaceholder('Enter your application name').fill('Test App');
    await page.getByPlaceholder('https://website.com/').click();
    await page.getByPlaceholder('https://website.com/').fill('https:facebook.com');
    await page.getByPlaceholder('https://website.com/').click();
    await page.getByText('Select category').click();
    await page.getByRole('main').getByText('Games').click();
    await page.getByRole('main').getByText('Social', { exact: true }).click();
    await page.getByRole('main').getByText('Finance').click();
    await page.locator('div').filter({ hasText: /^Games, Social, Finance$/ }).first().click();
    await page.getByPlaceholder('Enter a short app description').click();
    await page.getByPlaceholder('Enter a short app description').fill('test ha');
    await page.getByPlaceholder('Enter a description for your').click();
    await page.getByPlaceholder('Enter a description for your').fill('test ha');
    await page.getByPlaceholder('https://t.me/channel').click();
    await page.getByPlaceholder('https://t.me/channel').fill('https://testha.com');
    await page.locator('.flex > .relative > .flex').first().click();
    await page.locator('body').setInputFiles('386358963_2522555754573101_8518884904963479192_n.jpg');
    await page.locator('.swiper-slide > div > .relative > .flex > .text-sm').first().click();
    await page.locator('body').setInputFiles('387748414_2522556057906404_6039407820482571050_n.jpg');
    await page.locator('.swiper-slide > div > .relative > .flex').first().click();
    await page.locator('body').setInputFiles('386358963_2522555754573101_8518884904963479192_n.jpg');
    await page.locator('.swiper-slide > div > .relative > .flex').first().click();
    await page.locator('body').setInputFiles('386358963_2522555754573101_8518884904963479192_n.jpg');
    await page.getByRole('button', { name: 'Submit for review' }).click();
});